<?php

namespace FicheAchat\PlatformBundle\Repository;

/**
 * ficheAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ficheAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
